services:
  refinery:
    build: refinery
    ports:
      - 4317:4317
      - 8080:8080
    volumes:
      - ./config.yaml:/etc/refinery/config.yaml
      - ./rules.yaml:/etc/refinery/rules.yaml
      - ./refinery/connstats.sh:/ko-app/connstats.sh
    environment:
      - HONEYCOMB_API_KEY
    cap_add:
      - NET_ADMIN
      - NET_RAW
  loadgen:
    build: loadgen
    depends_on:
      - refinery
    command:
      - launcher.sh
      - --services
      - "500"
      - --tps
      - "3"
      - --runtime
      - "60"
    volumes:
      - ./loadgen/launcher.sh:/ko-app/launcher.sh
    environment:
      - HONEYCOMB_API_KEY
  # netshoot:
  #   image: nicolaka/netshoot
  #   entrypoint:
  #     - "sh"
  #   tty: true
  #   stdin_open: true
